import type { CafeStation } from "./types";

// Mock data shaped exactly like GET /api/cafes/near will return in STEP 2.
// Values match what the Nairobi seed produces so the swap to real data is
// purely mechanical — no UI changes required.
export const MOCK_CAFES: CafeStation[] = [
  // Westlands
  {
    id: "mock-1",
    name: "Java House Sarit Centre",
    neighbourhood: "Westlands",
    lat: -1.2603,
    lng: 36.8030,
    tier: "local",
    medianDownMbps: 31,
    medianUpMbps: 7.15,
    medianLatencyMs: 30,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/sarit-b/600/400",
    vibe: "weekday workhorse",
  },
  {
    id: "mock-2",
    name: "Artcaffe Westgate",
    neighbourhood: "Westlands",
    lat: -1.2566,
    lng: 36.8038,
    tier: "local",
    medianDownMbps: 21.5,
    medianUpMbps: 5.6,
    medianLatencyMs: 35.5,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/westgate-b/600/400",
    vibe: "lunch rush regular",
  },
  {
    id: "mock-3",
    name: "Connect Coffee Roasters",
    neighbourhood: "Westlands",
    lat: -1.2691,
    lng: 36.8108,
    tier: "express",
    medianDownMbps: 68.5,
    medianUpMbps: 17.2,
    medianLatencyMs: 15,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/connect-b/600/400",
    vibe: "the speed dealers",
  },
  // Kilimani
  {
    id: "mock-4",
    name: "Kaldi's Coffee Yaya",
    neighbourhood: "Kilimani",
    lat: -1.2935,
    lng: 36.7861,
    tier: "local",
    medianDownMbps: 36.5,
    medianUpMbps: 8.95,
    medianLatencyMs: 28,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/kaldi-b/600/400",
    vibe: "yaya regulars",
  },
  {
    id: "mock-5",
    name: "Brew Bistro Kilimani",
    neighbourhood: "Kilimani",
    lat: -1.2910,
    lng: 36.7895,
    tier: "suspended",
    medianDownMbps: 6,
    medianUpMbps: 1.6,
    medianLatencyMs: 91.5,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/brew-a/600/400",
    vibe: "loud at lunch",
  },
  {
    id: "mock-6",
    name: "About Thyme",
    neighbourhood: "Kilimani",
    lat: -1.2942,
    lng: 36.7916,
    tier: "express",
    medianDownMbps: 91.5,
    medianUpMbps: 23.25,
    medianLatencyMs: 12.5,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/thyme-b/600/400",
    vibe: "fibre + filter",
  },
  // CBD
  {
    id: "mock-7",
    name: "Java House Mama Ngina",
    neighbourhood: "CBD",
    lat: -1.2860,
    lng: 36.8211,
    tier: "local",
    medianDownMbps: 23,
    medianUpMbps: 5.6,
    medianLatencyMs: 37.5,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/mamangina-b/600/400",
    vibe: "downtown standby",
  },
  {
    id: "mock-8",
    name: "Savanna Coffee Lounge",
    neighbourhood: "CBD",
    lat: -1.2829,
    lng: 36.8243,
    tier: "express",
    medianDownMbps: 58.5,
    medianUpMbps: 14.5,
    medianLatencyMs: 17,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/savanna-b/600/400",
    vibe: "uptown for uplink",
  },
  {
    id: "mock-9",
    name: "Dormans Standard Street",
    neighbourhood: "CBD",
    lat: -1.2861,
    lng: 36.8225,
    tier: "suspended",
    medianDownMbps: 5,
    medianUpMbps: 1.35,
    medianLatencyMs: 93,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/dormans-a/600/400",
    vibe: "old school, slow lane",
  },
  // Karen
  {
    id: "mock-10",
    name: "Talisman",
    neighbourhood: "Karen",
    lat: -1.3217,
    lng: 36.7099,
    tier: "local",
    medianDownMbps: 30,
    medianUpMbps: 7.55,
    medianLatencyMs: 32,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/talisman-b/600/400",
    vibe: "garden over wires",
  },
  {
    id: "mock-11",
    name: "Karen Blixen Coffee Garden",
    neighbourhood: "Karen",
    lat: -1.3460,
    lng: 36.7020,
    tier: "express",
    medianDownMbps: 83,
    medianUpMbps: 21.1,
    medianLatencyMs: 14,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/blixen-b/600/400",
    vibe: "the book-wifi",
  },
  {
    id: "mock-12",
    name: "Java House The Hub Karen",
    neighbourhood: "Karen",
    lat: -1.3252,
    lng: 36.7186,
    tier: "local",
    medianDownMbps: 36.5,
    medianUpMbps: 9.1,
    medianLatencyMs: 27,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/hub-b/600/400",
    vibe: "mall route",
  },
];
