import type { CafeStation } from "./types";

// Mock venue data. Three cities: London/Shoreditch (launch market), Nairobi
// (legacy DB-backed fallback), and San Francisco (legacy mock-only).
//
// Same shape as `GET /api/cafes/near` returns. Adding a city is: pick real
// venues, tag them with `city: '<id>'` + `venueType`, and `getCafes({ city })`
// does the rest.

export const MOCK_CAFES: CafeStation[] = [
  // ── London / Shoreditch (launch market) ─────────────────────────────────────

  // Shoreditch High Street / Old Street
  {
    id: "ldn-1",
    name: "Ozone Coffee Roasters",
    neighbourhood: "Shoreditch",
    lat: 51.5257,
    lng: -0.0817,
    tier: "express",
    medianDownMbps: 82,
    medianUpMbps: 21.3,
    medianLatencyMs: 11,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 6,
    latestPhotoUrl: "https://picsum.photos/seed/ozone-ldn/600/400",
    venueType: "cafe",
    vibe: "roastery workspace",
    vibeTags: ["outlets++", "fibre", "pour-over"],
    city: "london",
    metadata: {
      priceTier: "mid",
      milkOptions: ["dairy", "oat", "soy"],
      powerOutlets: true,
      seating: "tables",
      noiseLevel: "moderate",
      tableSpace: "large",
    },
  },
  {
    id: "ldn-2",
    name: "Prufrock at the Barbican",
    neighbourhood: "Shoreditch",
    lat: 51.5197,
    lng: -0.0937,
    tier: "local",
    medianDownMbps: 34,
    medianUpMbps: 8.5,
    medianLatencyMs: 15,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/prufrock-ldn/600/400",
    venueType: "cafe",
    vibe: "specialty quiet",
    vibeTags: ["quiet", "pour-over", "oat-milk"],
    city: "london",
    metadata: {
      priceTier: "premium",
      milkOptions: ["dairy", "oat", "almond"],
      powerOutlets: true,
      seating: "mixed",
      noiseLevel: "quiet",
      tableSpace: "standard",
    },
  },
  {
    id: "ldn-3",
    name: "Allpress London",
    neighbourhood: "Shoreditch",
    lat: 51.5243,
    lng: -0.0728,
    tier: "express",
    medianDownMbps: 74,
    medianUpMbps: 19.1,
    medianLatencyMs: 12,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 5,
    latestPhotoUrl: "https://picsum.photos/seed/allpress-ldn/600/400",
    venueType: "cafe",
    vibe: "roastery tables",
    vibeTags: ["fibre", "outlets++", "brunch"],
    city: "london",
    metadata: {
      priceTier: "mid",
      milkOptions: ["dairy", "oat"],
      powerOutlets: true,
      seating: "tables",
      noiseLevel: "moderate",
      tableSpace: "standard",
    },
  },
  {
    id: "ldn-4",
    name: "WeWork Old Street",
    neighbourhood: "Shoreditch",
    lat: 51.5259,
    lng: -0.0887,
    tier: "express",
    medianDownMbps: 192,
    medianUpMbps: 89,
    medianLatencyMs: 6,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 8,
    latestPhotoUrl: "https://picsum.photos/seed/wework-oldstreet/600/400",
    venueType: "coworking",
    vibe: "coworking fast lane",
    vibeTags: ["fibre", "outlets++", "meeting-rooms"],
    city: "london",
    metadata: {
      priceTier: "premium",
      milkOptions: ["dairy", "oat", "soy"],
      powerOutlets: true,
      seating: "mixed",
      noiseLevel: "quiet",
      tableSpace: "large",
    },
    sponsor: {
      name: "WeWork",
      kind: "café",
      tagline: "Day passes available via app",
    },
  },
  {
    id: "ldn-5",
    name: "The Hoxton Hotel Lobby",
    neighbourhood: "Shoreditch",
    lat: 51.5248,
    lng: -0.0814,
    tier: "local",
    medianDownMbps: 42,
    medianUpMbps: 10.2,
    medianLatencyMs: 18,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/hoxton-lobby/600/400",
    venueType: "hotel-lobby",
    vibe: "laptop friendly lobby",
    vibeTags: ["hotel", "outlets++", "quiet"],
    city: "london",
    metadata: {
      priceTier: "premium",
      milkOptions: ["dairy", "oat"],
      powerOutlets: true,
      seating: "lounge",
      noiseLevel: "moderate",
      tableSpace: "standard",
    },
  },
  {
    id: "ldn-6",
    name: "Shoreditch Grind",
    neighbourhood: "Shoreditch",
    lat: 51.5263,
    lng: -0.0847,
    tier: "suspended",
    medianDownMbps: 7,
    medianUpMbps: 1.8,
    medianLatencyMs: 78,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 3,
    latestPhotoUrl: "https://picsum.photos/seed/shoreditch-grind/600/400",
    venueType: "cafe",
    vibe: "buzzy corner",
    vibeTags: ["buzzy", "brunch", "pastry"],
    city: "london",
    metadata: {
      priceTier: "mid",
      milkOptions: ["dairy", "oat"],
      powerOutlets: false,
      seating: "tables",
      noiseLevel: "loud",
      tableSpace: "small",
    },
  },

  // ── Nairobi ────────────────────────────────────────────────────────────────

  // Westlands
  {
    id: "mock-1",
    name: "Java House Sarit Centre",
    neighbourhood: "Westlands",
    lat: -1.2603,
    lng: 36.8030,
    tier: "local",
    medianDownMbps: 31,
    medianUpMbps: 7.15,
    medianLatencyMs: 30,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/sarit-b/600/400",
    vibe: "weekday workhorse",
    vibeTags: ["outlets++", "mall", "brunch"],
    city: "nairobi",
  },
  {
    id: "mock-2",
    name: "Artcaffe Westgate",
    neighbourhood: "Westlands",
    lat: -1.2566,
    lng: 36.8038,
    tier: "local",
    medianDownMbps: 21.5,
    medianUpMbps: 5.6,
    medianLatencyMs: 35.5,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/westgate-b/600/400",
    vibe: "lunch rush regular",
    vibeTags: ["buzzy", "mall", "brunch"],
    city: "nairobi",
  },
  {
    id: "mock-3",
    name: "Connect Coffee Roasters",
    neighbourhood: "Westlands",
    lat: -1.2691,
    lng: 36.8108,
    tier: "express",
    medianDownMbps: 68.5,
    medianUpMbps: 17.2,
    medianLatencyMs: 15,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/connect-b/600/400",
    vibe: "the speed dealers",
    vibeTags: ["fibre", "pour-over", "quiet"],
    city: "nairobi",
    sponsor: {
      name: "Safaricom Fibre",
      kind: "isp",
      tagline: "Powered by 1 Gbps home fibre",
    },
  },
  // Kilimani
  {
    id: "mock-4",
    name: "Kaldi's Coffee Yaya",
    neighbourhood: "Kilimani",
    lat: -1.2935,
    lng: 36.7861,
    tier: "local",
    medianDownMbps: 36.5,
    medianUpMbps: 8.95,
    medianLatencyMs: 28,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/kaldi-b/600/400",
    vibe: "yaya regulars",
    vibeTags: ["outlets++", "mall", "oat-milk"],
    city: "nairobi",
  },
  {
    id: "mock-5",
    name: "Brew Bistro Kilimani",
    neighbourhood: "Kilimani",
    lat: -1.2910,
    lng: 36.7895,
    tier: "suspended",
    medianDownMbps: 6,
    medianUpMbps: 1.6,
    medianLatencyMs: 91.5,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/brew-a/600/400",
    vibe: "loud at lunch",
    vibeTags: ["buzzy", "late-night", "view"],
    city: "nairobi",
  },
  {
    id: "mock-6",
    name: "About Thyme",
    neighbourhood: "Kilimani",
    lat: -1.2942,
    lng: 36.7916,
    tier: "express",
    medianDownMbps: 91.5,
    medianUpMbps: 23.25,
    medianLatencyMs: 12.5,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/thyme-b/600/400",
    vibe: "fibre + filter",
    vibeTags: ["fibre", "garden", "pour-over"],
    city: "nairobi",
  },
  // CBD
  {
    id: "mock-7",
    name: "Java House Mama Ngina",
    neighbourhood: "CBD",
    lat: -1.2860,
    lng: 36.8211,
    tier: "local",
    medianDownMbps: 23,
    medianUpMbps: 5.6,
    medianLatencyMs: 37.5,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/mamangina-b/600/400",
    vibe: "downtown standby",
    vibeTags: ["central", "outlets++", "brunch"],
    city: "nairobi",
  },
  {
    id: "mock-8",
    name: "Savanna Coffee Lounge",
    neighbourhood: "CBD",
    lat: -1.2829,
    lng: 36.8243,
    tier: "express",
    medianDownMbps: 58.5,
    medianUpMbps: 14.5,
    medianLatencyMs: 17,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/savanna-b/600/400",
    vibe: "uptown for uplink",
    vibeTags: ["fibre", "central", "quiet"],
    city: "nairobi",
  },
  {
    id: "mock-9",
    name: "Dormans Standard Street",
    neighbourhood: "CBD",
    lat: -1.2861,
    lng: 36.8225,
    tier: "suspended",
    medianDownMbps: 5,
    medianUpMbps: 1.35,
    medianLatencyMs: 93,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/dormans-a/600/400",
    vibe: "old school, slow lane",
    vibeTags: ["classic", "central", "pastry"],
    city: "nairobi",
  },
  // Karen
  {
    id: "mock-10",
    name: "Talisman",
    neighbourhood: "Karen",
    lat: -1.3217,
    lng: 36.7099,
    tier: "local",
    medianDownMbps: 30,
    medianUpMbps: 7.55,
    medianLatencyMs: 32,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/talisman-b/600/400",
    vibe: "garden over wires",
    vibeTags: ["garden", "brunch", "view"],
    city: "nairobi",
  },
  {
    id: "mock-11",
    name: "Karen Blixen Coffee Garden",
    neighbourhood: "Karen",
    lat: -1.3460,
    lng: 36.7020,
    tier: "express",
    medianDownMbps: 83,
    medianUpMbps: 21.1,
    medianLatencyMs: 14,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/blixen-b/600/400",
    vibe: "the book-wifi",
    vibeTags: ["garden", "quiet", "view"],
    city: "nairobi",
  },
  {
    id: "mock-12",
    name: "Java House The Hub Karen",
    neighbourhood: "Karen",
    lat: -1.3252,
    lng: 36.7186,
    tier: "local",
    medianDownMbps: 36.5,
    medianUpMbps: 9.1,
    medianLatencyMs: 27,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 4,
    latestPhotoUrl: "https://picsum.photos/seed/hub-b/600/400",
    vibe: "mall route",
    vibeTags: ["mall", "outlets++", "brunch"],
    city: "nairobi",
  },

  // ── San Francisco ──────────────────────────────────────────────────────────
  // 12 real cafés the local tech crowd will recognize. Tier assignments are
  // educated guesses based on each spot's reputation, not measured ground
  // truth — the live engine would correct these the moment real contributors
  // log readings.

  // SOMA / FiDi
  {
    id: "sf-1",
    name: "Sightglass Coffee SOMA",
    neighbourhood: "SOMA",
    lat: 37.7752,
    lng: -122.4083,
    tier: "express",
    medianDownMbps: 72,
    medianUpMbps: 18.4,
    medianLatencyMs: 13,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/sightglass/600/400",
    vibe: "the glassworks",
    vibeTags: ["fibre", "pour-over", "espresso"],
    city: "sf",
  },
  {
    id: "sf-2",
    name: "Mazarine Coffee",
    neighbourhood: "FiDi",
    lat: 37.7888,
    lng: -122.4001,
    tier: "express",
    medianDownMbps: 96,
    medianUpMbps: 24.6,
    medianLatencyMs: 10,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/mazarine/600/400",
    vibe: "screen-time fortress",
    vibeTags: ["fibre", "outlets++", "quiet"],
    city: "sf",
    sponsor: {
      name: "Sonic.net",
      kind: "isp",
      tagline: "Powered by 10 Gbps symmetric fibre",
    },
  },
  {
    id: "sf-3",
    name: "Blue Bottle Mint Plaza",
    neighbourhood: "SOMA",
    lat: 37.7826,
    lng: -122.4081,
    tier: "local",
    medianDownMbps: 38,
    medianUpMbps: 9.6,
    medianLatencyMs: 24,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/bluebottle-mint/600/400",
    vibe: "weekday rotation",
    vibeTags: ["pour-over", "brunch", "central"],
    city: "sf",
  },

  // Mission
  {
    id: "sf-4",
    name: "Ritual Coffee Roasters Mission",
    neighbourhood: "Mission",
    lat: 37.7569,
    lng: -122.4214,
    tier: "express",
    medianDownMbps: 64,
    medianUpMbps: 15.8,
    medianLatencyMs: 18,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/ritual-mission/600/400",
    vibe: "valencia laptop class",
    vibeTags: ["fibre", "outlets++", "pour-over"],
    city: "sf",
  },
  {
    id: "sf-5",
    name: "Verve Coffee Roasters Mission",
    neighbourhood: "Mission",
    lat: 37.7625,
    lng: -122.4194,
    tier: "local",
    medianDownMbps: 28,
    medianUpMbps: 7.2,
    medianLatencyMs: 32,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/verve-mission/600/400",
    vibe: "saturday saturated",
    vibeTags: ["brunch", "pastry", "buzzy"],
    city: "sf",
  },
  {
    id: "sf-6",
    name: "Linea Caffe",
    neighbourhood: "Mission",
    lat: 37.7615,
    lng: -122.4254,
    tier: "local",
    medianDownMbps: 33,
    medianUpMbps: 8.4,
    medianLatencyMs: 28,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/linea/600/400",
    vibe: "calle dieciocho",
    vibeTags: ["quiet", "pour-over", "espresso"],
    city: "sf",
  },

  // Russian Hill / Hayes
  {
    id: "sf-7",
    name: "Saint Frank Coffee Polk",
    neighbourhood: "Russian Hill",
    lat: 37.7984,
    lng: -122.4220,
    tier: "express",
    medianDownMbps: 81,
    medianUpMbps: 20.5,
    medianLatencyMs: 12,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/saintfrank/600/400",
    vibe: "polk hill ritual",
    vibeTags: ["fibre", "pour-over", "quiet"],
    city: "sf",
  },
  {
    id: "sf-8",
    name: "Réveille Coffee Hayes Valley",
    neighbourhood: "Hayes Valley",
    lat: 37.7757,
    lng: -122.4255,
    tier: "local",
    medianDownMbps: 35,
    medianUpMbps: 8.8,
    medianLatencyMs: 27,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/reveille-hayes/600/400",
    vibe: "octavia regulars",
    vibeTags: ["garden", "brunch", "oat-milk"],
    city: "sf",
  },
  {
    id: "sf-9",
    name: "The Coffee Movement",
    neighbourhood: "Nob Hill",
    lat: 37.7956,
    lng: -122.4101,
    tier: "local",
    medianDownMbps: 26,
    medianUpMbps: 6.5,
    medianLatencyMs: 34,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/coffee-movement/600/400",
    vibe: "nob hill pour",
    vibeTags: ["pour-over", "quiet", "espresso"],
    city: "sf",
  },

  // Marina / Outer
  {
    id: "sf-10",
    name: "Wrecking Ball Coffee Roasters",
    neighbourhood: "Marina",
    lat: 37.7976,
    lng: -122.4360,
    tier: "local",
    medianDownMbps: 31,
    medianUpMbps: 7.9,
    medianLatencyMs: 30,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/wreckingball/600/400",
    vibe: "union street pour",
    vibeTags: ["buzzy", "brunch", "view"],
    city: "sf",
  },
  {
    id: "sf-11",
    name: "The Mill",
    neighbourhood: "NoPa",
    lat: 37.7763,
    lng: -122.4373,
    tier: "suspended",
    medianDownMbps: 6.5,
    medianUpMbps: 1.7,
    medianLatencyMs: 88,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/themill/600/400",
    vibe: "loaves before wifi",
    vibeTags: ["pastry", "brunch", "buzzy"],
    city: "sf",
  },
  {
    id: "sf-12",
    name: "Andytown Coffee Roasters",
    neighbourhood: "Outer Sunset",
    lat: 37.7547,
    lng: -122.4933,
    tier: "suspended",
    medianDownMbps: 7.5,
    medianUpMbps: 2.1,
    medianLatencyMs: 76,
    medianJitterMs: 0,
    medianLossPct: 0,
    measurementCount: 0,
    latestPhotoUrl: "https://picsum.photos/seed/andytown/600/400",
    vibe: "ocean fog brew",
    vibeTags: ["view", "pastry", "brunch"],
    city: "sf",
  },
];
