export type Tier = "express" | "local" | "suspended";

// How a measurement was captured. 'manual' = contributor typed numbers from
// an external tool. 'browser-auto' = the in-app speed test ran the download /
// upload / ping sampling and submitted the result. The API derives this
// server-side from the presence of auto-test metadata, never trusting the
// client's claim alone.
export type TestMethod = "manual" | "browser-auto";

// The speed readings that both the in-app speed test and the manual form
// produce. The single source of truth shared between lib/speedtest.ts,
// components/measurement-form.tsx, and app/api/measurements/route.ts.
// jitter/loss are optional — manual entries won't have them, and early
// auto-test phases may skip upload.
export interface MeasurementReading {
  downMbps: number;
  upMbps: number;
  latencyMs: number;
  jitterMs?: number;
  lossPct?: number;
}

// What the API accepts on POST /api/measurements. Extends the reading with
// provenance metadata. device_type is NOT here — it's derived server-side
// from the User-Agent so it can't be spoofed.
export interface MeasurementInput extends MeasurementReading {
  cafeId: string;
  /** ISO 8601. Defaults to server-now if omitted. */
  measuredAt?: string;
  contributorId?: string;
  /** Optional. Real upload pipeline (S3 presigned) lands later. */
  photoUrl?: string;
  testMethod?: TestMethod;
  /** Which edge served the speed test (e.g. Vercel edge region id). */
  targetServer?: string;
  /** Bytes transferred in the download phase, for transparency. */
  downloadBytes?: number;
  /** Download phase duration in ms, for transparency. */
  downloadDurationMs?: number;
}

// String, not enum — different cities have different neighbourhoods and we
// don't want to centralise that here. The map UI only uses neighbourhood
// names for label rendering, not for layout decisions.
export type Neighbourhood = string;

// City identifier. Curated cities (nairobi, sf) have entries in CITIES with
// schematic layouts. User-generated cities are arbitrary strings derived
// from coordinates — they get transit maps generated by computeWaypoints.
export type CityId = string;

export type TimeBucket = "morning" | "afternoon" | "evening";

// Coffee metadata that a contributor provides when mapping a new café.
// Single source of truth — validation lives in lib/cafe-metadata.ts.
export interface CafeMetadata {
  priceTier?: "budget" | "mid" | "premium";
  milkOptions?: string[];
  powerOutlets?: boolean;
  seating?: "bar" | "tables" | "lounge" | "mixed";
  wifiNetwork?: string;
}

// Input for creating a new café via POST /api/cafes. The measurement is
// mandatory — a café doesn't exist on the map until it has at least one
// real speed reading.
export interface CafeCreationInput {
  name: string;
  neighbourhood: string;
  lat: number;
  lng: number;
  city?: string;
  vibe?: string;
  metadata: CafeMetadata;
  photo: string;
  measurement: MeasurementInput;
}

// Mirrors the row shape that GET /api/cafes/near returns.
// Kept intentionally identical to the cafe_speed_stats view plus the
// latest photo_url join.
export interface CafeStation {
  id: string;
  name: string;
  neighbourhood: Neighbourhood;
  lat: number;
  lng: number;
  tier: Tier;
  medianDownMbps: number;
  medianUpMbps: number;
  medianLatencyMs: number;
  /** Median jitter across all auto-test readings. 0 when no auto readings. */
  medianJitterMs: number;
  /** Median packet loss % across all auto-test readings. 0 when no auto readings. */
  medianLossPct: number;
  measurementCount: number;
  latestPhotoUrl: string | null;
  /** Short editorial descriptor — the café's "atmosphere" in 2-4 words.
   *  Surfaced on station cards and in the map hover state. Stored in DB
   *  alongside the rest of the cafés metadata; STEP 2 will SELECT it. */
  vibe: string;
  /** Compact, fixed-vocabulary chips that ride alongside `vibe`. Two or
   *  three per café — what you'd put on a transit-poster sticker. Optional
   *  because DB rows don't carry them yet; the mock backfill does, and the
   *  hackathon demo path runs through mock data when Aurora is cold. */
  vibeTags?: string[];
  /** The city this café belongs to. Curated cities have entries in CITIES;
   *  user-generated cities are arbitrary strings. */
  city: CityId;
  /** Coffee metadata — price, milk, power, seating. Optional because
   *  seeded cafés and early contributions may not include it. */
  metadata?: CafeMetadata;
  /** Photo of the café or the contributor's coffee — Base64 data URL.
   *  Serves as proof-of-presence verification. */
  photoUrl?: string | null;
}

// Returned by GET /api/cafes/[id] — detail + distribution by time bucket.
export interface CafeDetail extends CafeStation {
  distribution: Array<{
    timeBucket: TimeBucket;
    medianDownMbps: number;
    sampleSize: number;
  }>;
  /** The most recent measurements at this café — up to 5 newest-first.
   *  Surfaced as a live "last brewed" ticker on the detail drawer + page.
   *  Empty array when there are no readings (e.g. SF reputation tiers). */
  recent: Array<{ measuredAt: string; downMbps: number }>;
}
