export type Tier = "express" | "local" | "suspended";

// Nimiq bounty lifecycle states. Bounties are created open, briefly locked
// while a payout is in flight, and marked paid once the transaction lands.
export type BountyStatus = "open" | "claiming" | "paid";

// How a measurement was captured. 'manual' = contributor typed numbers from
// an external tool. 'browser-auto' = the in-app speed test ran the download /
// upload / ping sampling and submitted the result. The API derives this
// server-side from the presence of auto-test metadata, never trusting the
// client's claim alone.
export type TestMethod = "manual" | "browser-auto";

// The speed readings that both the in-app speed test and the manual form
// produce. The single source of truth shared between lib/speedtest.ts,
// components/measurement-form.tsx, and app/api/measurements/route.ts.
// jitter/loss are optional — manual entries won't have them, and early
// auto-test phases may skip upload.
export interface MeasurementReading {
  downMbps: number;
  upMbps: number;
  latencyMs: number;
  jitterMs?: number;
  lossPct?: number;
}

// What the API accepts on POST /api/measurements. Extends the reading with
// provenance metadata. device_type is NOT here — it's derived server-side
// from the User-Agent so it can't be spoofed.
export interface MeasurementInput extends MeasurementReading {
  cafeId: string;
  /** ISO 8601. Defaults to server-now if omitted. */
  measuredAt?: string;
  contributorId?: string;
  /** Optional. Real upload pipeline (S3 presigned) lands later. */
  photoUrl?: string;
  testMethod?: TestMethod;
  /** Which edge served the speed test (e.g. Vercel edge region id). */
  targetServer?: string;
  /** Bytes transferred in the download phase, for transparency. */
  downloadBytes?: number;
  /** Download phase duration in ms, for transparency. */
  downloadDurationMs?: number;
}

// String, not enum — different cities have different neighbourhoods and we
// don't want to centralise that here. The map UI only uses neighbourhood
// names for label rendering, not for layout decisions.
export type Neighbourhood = string;

// City identifier. Curated cities (nairobi, sf) have entries in CITIES with
// schematic layouts. User-generated cities are arbitrary strings derived
// from coordinates — they get transit maps generated by computeWaypoints.
export type CityId = string;

export type TimeBucket = "morning" | "afternoon" | "evening";

// Types of venues Lattency supports. We started with cafés, but the engine
// works for any coffee-adjacent workspace.
export type VenueType = "cafe" | "coworking" | "hotel-lobby" | "library" | "hybrid";

// Workspace metadata that a contributor provides when mapping a new venue.
// Single source of truth — validation lives in lib/cafe-metadata.ts.
//
// We deliberately keep this objective and verifiable. No subjective
// "coffee quality" ratings. If it can’t be observed or measured, it’s out.
export interface CafeMetadata {
  priceTier?: "budget" | "mid" | "premium";
  milkOptions?: string[];
  powerOutlets?: boolean;
  seating?: "bar" | "tables" | "lounge" | "mixed";
  wifiNetwork?: string;
  /** How loud the space is when moderately busy. */
  noiseLevel?: "quiet" | "moderate" | "loud";
  /** How much table space a laptop worker can realistically expect. */
  tableSpace?: "small" | "standard" | "large";
}

// Input for creating a new venue via POST /api/cafes. The measurement is
// mandatory — a venue doesn't exist on the map until it has at least one
// real speed reading.
export interface CafeCreationInput {
  name: string;
  neighbourhood: string;
  lat: number;
  lng: number;
  city?: string;
  venueType?: VenueType;
  vibe?: string;
  metadata: CafeMetadata;
  photo: string;
  measurement: MeasurementInput;
}

// Mirrors the row shape that GET /api/cafes/near returns.
// Kept intentionally identical to the cafe_speed_stats view plus the
// latest photo_url join.
export interface CafeStation {
  id: string;
  name: string;
  neighbourhood: Neighbourhood;
  lat: number;
  lng: number;
  tier: Tier;
  medianDownMbps: number;
  medianUpMbps: number;
  medianLatencyMs: number;
  /** Median jitter across all auto-test readings. 0 when no auto readings. */
  medianJitterMs: number;
  /** Median packet loss % across all auto-test readings. 0 when no auto readings. */
  medianLossPct: number;
  measurementCount: number;
  latestPhotoUrl: string | null;
  /** What kind of workspace this is. We default to cafe for backward
   *  compatibility, but the engine supports coworking, hotel lobbies, etc. */
  venueType?: VenueType;
  /** Short editorial descriptor — the venue's "atmosphere" in 2-4 words.
   *  Surfaced on station cards and in the map hover state. Stored in DB
   *  alongside the rest of the venue metadata; STEP 2 will SELECT it. */
  vibe: string;
  /** Compact, fixed-vocabulary chips that ride alongside `vibe`. Two or
   *  three per venue — what you'd put on a transit-poster sticker. Optional
   *  because DB rows don't carry them yet; the mock backfill does, and the
   *  hackathon demo path runs through mock data when Base44 is cold. */
  vibeTags?: string[];
  /** The city this venue belongs to. Curated cities have entries in CITIES;
   *  user-generated cities are arbitrary strings. */
  city: CityId;
  /** Workspace metadata — price, milk, power, seating, noise, table space.
   *  Optional because seeded venues and early contributions may not include it. */
  metadata?: CafeMetadata;
  /** Photo of the venue or the contributor's coffee — Base64 data URL.
   *  Gives the venue page a face. The mandatory speed test is the actual
   *  trust mechanism; the photo is presentation. */
  photoUrl?: string | null;
  /** Active sponsorship for this venue, joined from `sponsorships`. Null when
   *  no sponsor is currently attached. */
  sponsor?: Sponsor | null;
  /** ISO timestamp of the most recent measurement. Used for staleness decay
   *  — stations visually fade after 14 days without a fresh reading. Optional
   *  because mock data backfills it but the DB path may not return it yet. */
  lastReadingAt?: string;
}

// One active sponsor per café (the partial unique index in migration 0007
// enforces this for v1). Surfaced via the LEFT JOIN in the cafe_speed_stats
// materialized view so the read path is one query, not N+1.
export interface Sponsor {
  name: string;
  kind: "isp" | "café" | "community" | "anon";
  tagline: string | null;
}

// Address returned by Nimiq Mini App SDK's listAccounts(). The SDK hides
// private keys; we only ever see the public address.
export interface NimiqAccount {
  address: string;
  label: string;
}

// Measurement POST response when the reading completed one or more bounties.
export interface CompletedBounty {
  bountyId: string;
  goal: string;
  rewardLunas: number;
  rewardNim: number;
}

// Returned by GET /api/cafes/[id] — detail + distribution by time bucket.
export interface CafeDetail extends CafeStation {
  distribution: Array<{
    timeBucket: TimeBucket;
    medianDownMbps: number;
    sampleSize: number;
  }>;
  /** The most recent measurements at this café — up to 5 newest-first.
   *  Surfaced as a live "last brewed" ticker on the detail drawer + page.
   *  Empty array when there are no readings (e.g. SF reputation tiers). */
  recent: Array<{ measuredAt: string; downMbps: number }>;
}
