import { executeNimiqPayout } from "@/lib/nimiq-payout";

/**
 * Test a real Nimiq testnet payout using the escrow wallet generated by
 * `generate-nimiq-wallet.ts` and funded by the testnet faucet.
 *
 * Run with:
 *   NIMIQ_PRIVATE_KEY=<hex> NIMIQ_PAYOUT_MOCK=0 pnpm exec tsx scripts/test-payout.ts
 */
async function main() {
  const recipient = "NQ44 Q0KX N6Q3 NJS6 6J9S 6RA9 XR04 TKL7 PGM9";
  const result = await executeNimiqPayout(recipient, 0.01);
  console.log("Payout result:", result);
}

main().catch((err) => {
  console.error("Payout failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
